#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez


# export LIBGL_ALWAYS_INDIRECT=true
eval `cat ~/.fehbg`
setxkbmap -layout us,se -option ctrl:nocaps,grp:menu_toggle,grp_led:scroll
PPP=$(xinput list | grep -iv 'wacom' | egrep "slave.*pointer" | grep -v XTEST | sed -e 's/^.*id=//' -e 's/\s.*$//')
xinput set-button-map $PPP 1 2 3 5 4 6 7 8 9 10 11 12
xsetroot -bg black
#xautolock -time 3 -locker 'i3lock -n -d -c ffffff' -corners 0+-0 -nowlocker 'i3lock -n -d -c ffffff' -cornerdelay 3 -cornerredelay 10 -secure
xsetroot -cursor_name left_ptr

