#!/bin/bash

dev='/sys/class/backlight/acpi_video0/brightness'
curr_bright=$(cat /sys/class/backlight/acpi_video0/brightness)
max_bright=$(cat /sys/class/backlight/acpi_video0/max_brightness)


case $1 in
	up)
	[ $curr_bright == $max_bright ] && exit 0
	echo $((curr_bright+1)) | sudo tee $dev 1> /dev/null
	;;
	down)
	[ $curr_bright == 0 ] && exit 0
	echo $((curr_bright-1)) | sudo tee $dev 1> /dev/null
	;;
	*)
	;;
esac

